-- PostgreSQL + pgvector Schema for RAG System
-- Database: ragdb
-- Author: Luis Felipe de Moraes
-- Date: 2026-06-09
--
-- Usage:
--   PGPASSWORD=postgres123 psql -h localhost -U postgres -d ragdb -f create_database_schema.sql

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Drop existing tables (use with caution in production!)
DROP TABLE IF EXISTS document_chunks CASCADE;
DROP TABLE IF EXISTS news_documents CASCADE;

-- ===================================
-- Table: news_documents
-- ===================================
-- Stores document metadata and full content

CREATE TABLE news_documents (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    url TEXT UNIQUE,  -- IMPORTANT: unique constraint for ON CONFLICT
    source_agency TEXT,
    category TEXT,
    published_at TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NOW(),
    metadata JSONB,
    indexed_at TIMESTAMP DEFAULT NOW()
);

COMMENT ON TABLE news_documents IS 'Stores metadata and full content of news documents';
COMMENT ON COLUMN news_documents.url IS 'Unique URL - used for deduplication in indexing';
COMMENT ON COLUMN news_documents.metadata IS 'Additional metadata in JSON format (tags, etc)';

-- ===================================
-- Table: document_chunks
-- ===================================
-- Stores text chunks with vector embeddings

CREATE TABLE document_chunks (
    id SERIAL PRIMARY KEY,
    document_id INTEGER NOT NULL REFERENCES news_documents(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    enriched_content TEXT,  -- Optional: LLM-enriched version
    embedding vector(1024),  -- BGE-M3 embeddings (1024 dimensions)
    chunk_type TEXT,  -- semantic, fixed, sentence, etc
    char_start INTEGER,  -- Start position in original document
    char_end INTEGER,  -- End position in original document
    tokens INTEGER,  -- Token count
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(document_id, chunk_index)
);

COMMENT ON TABLE document_chunks IS 'Text chunks with vector embeddings for semantic search';
COMMENT ON COLUMN document_chunks.embedding IS 'Vector embedding (1024d) generated by BGE-M3';
COMMENT ON COLUMN document_chunks.enriched_content IS 'Optional LLM-enriched version for better retrieval';

-- ===================================
-- Indexes - Basic
-- ===================================

-- Foreign key index
CREATE INDEX idx_chunks_document_id ON document_chunks(document_id);

-- Category filtering
CREATE INDEX idx_documents_category ON news_documents(category);

-- URL lookup
CREATE INDEX idx_documents_url ON news_documents(url);

-- Date range queries
CREATE INDEX idx_documents_published ON news_documents(published_at DESC);

-- Source agency filtering
CREATE INDEX idx_documents_agency ON news_documents(source_agency);

-- ===================================
-- Vector Index (HNSW)
-- ===================================
-- Create AFTER inserting data for better performance
-- Uncomment and run after indexing documents:

-- CREATE INDEX idx_chunks_embedding ON document_chunks
--   USING hnsw (embedding vector_cosine_ops)
--   WITH (m = 16, ef_construction = 64);

-- Alternative: IVFFlat (faster build, slower search)
-- CREATE INDEX idx_chunks_embedding ON document_chunks
--   USING ivfflat (embedding vector_cosine_ops)
--   WITH (lists = 100);

-- ===================================
-- Full-Text Search Setup
-- ===================================
-- Add tsvector column for Portuguese full-text search

ALTER TABLE document_chunks ADD COLUMN IF NOT EXISTS tsv tsvector;

-- Create GIN index for full-text search
CREATE INDEX IF NOT EXISTS idx_chunks_fts ON document_chunks USING GIN(tsv);

-- Create trigger to auto-update tsvector
CREATE OR REPLACE FUNCTION chunks_tsv_trigger() RETURNS trigger AS $$
BEGIN
  NEW.tsv := to_tsvector('portuguese', COALESCE(NEW.content, ''));
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tsvectorupdate ON document_chunks;
CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE ON document_chunks
  FOR EACH ROW EXECUTE FUNCTION chunks_tsv_trigger();

COMMENT ON COLUMN document_chunks.tsv IS 'Automatically generated tsvector for Portuguese full-text search';

-- ===================================
-- Performance Tuning
-- ===================================

-- Update statistics
ANALYZE news_documents;
ANALYZE document_chunks;

-- ===================================
-- Verification Queries
-- ===================================

-- Check extensions
SELECT * FROM pg_extension WHERE extname = 'vector';

-- Check tables
\dt

-- Check indexes
\di

-- Sample query: Find similar chunks
-- SELECT id, content, embedding <=> '[0.1, 0.2, ...]'::vector as distance
-- FROM document_chunks
-- ORDER BY distance
-- LIMIT 10;

-- Full-text search example
-- SELECT id, content, ts_rank_cd(tsv, query) as rank
-- FROM document_chunks, websearch_to_tsquery('portuguese', 'sua busca') query
-- WHERE tsv @@ query
-- ORDER BY rank DESC
-- LIMIT 10;

-- ===================================
-- Grants (if using specific users)
-- ===================================

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres;

-- For read-only user (optional):
-- CREATE USER rag_readonly WITH PASSWORD 'readonly_password';
-- GRANT CONNECT ON DATABASE ragdb TO rag_readonly;
-- GRANT SELECT ON ALL TABLES IN SCHEMA public TO rag_readonly;
